compute_environment: LOCAL_MACHINE
deepspeed_config:
  deepspeed_config_file: util/deepspeed_configs/zero_stage2_config.json
distributed_type: DEEPSPEED
fsdp_config: {}
gpu_ids: 0,1,2,3,4,5,6,7
machine_rank: 0
main_process_ip: null
main_process_port: 12350
main_training_function: main
num_machines: 1
num_processes: 8
use_cpu: false
